# Generated by Django 2.1.7 on 2019-02-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Tour Guide', max_length=50),
        ),
    ]
