# Generated by Django 2.2.2 on 2019-06-17 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=50, verbose_name='名前')),
                ('is_group', models.BooleanField(default=True, verbose_name='グループ予約')),
                ('group_name', models.CharField(max_length=100, null=True, verbose_name='グループ名前')),
                ('group_number', models.IntegerField(null=True, verbose_name='グループの数')),
                ('contact_number', models.CharField(max_length=50, verbose_name='電話番号')),
                ('contact_address', models.TextField(verbose_name='住所')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('scheduled_at', models.DateTimeField(verbose_name='予定時間')),
                ('duration', models.CharField(max_length=50, verbose_name='期間\x1c（分）')),
                ('age_group', models.CharField(choices=[('家族', '家族'), ('大人', '大人'), ('高齢者', '高齢者'), ('子供・思春期', '子供・思春期'), ('ミックス', 'ミックス')], max_length=50, verbose_name='年齢層')),
                ('places_to_visit', models.TextField(verbose_name='訪問したい酒蔵')),
                ('transportation', models.CharField(choices=[('使う交通手段', '使う交通手段'), ('電車', '電車'), ('コーチ', 'コーチ'), ('自動車・バン', '自動車・バン'), ('タクシ', 'タクシ'), ('その他', '他の交通手段\x1c（”他に伝えたい情報”で伝えてください。）')], max_length=50, verbose_name='使う交通手段')),
                ('extra_details', models.TextField(verbose_name='他に伝えたい情報')),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='予約をとった時間')),
                ('confirmed', models.BooleanField(default=False, verbose_name='確認されたが')),
                ('complete', models.BooleanField(default=False, verbose_name='完成した')),
            ],
            options={
                'ordering': ['-scheduled_at', '-booked_at', 'confirmed'],
            },
        ),
    ]
