# Generated by Django 2.2.2 on 2019-06-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190622_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(max_length=50, verbose_name='期間・分'),
        ),
    ]
