# Generated by Django 2.2.2 on 2019-06-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190622_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(verbose_name='期間・分'),
        ),
    ]
