# Generated by Django 2.2 on 2019-04-01 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿時間')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間')),
                ('pinned', models.BooleanField(default=False, verbose_name='重要')),
                ('admin_post', models.BooleanField(default=False, verbose_name='管理者向き')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='by', to=settings.AUTH_USER_MODEL, verbose_name='著者')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=50, verbose_name='名前')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿時間')),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間')),
                ('by_admin', models.BooleanField(default=False, verbose_name='管理者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post', verbose_name='ポスト')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
